eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: erp-auth-client
security:
  oauth2:
    resource:
      user-info-uri: http://127.0.0.1:9098/user/current
    client:
      id: client_2
      client-secret: 123456
      access-token-uri: http://127.0.0.1:9098/oauth/token
      grant-type: client_credentials,password
      scope: server